# 全局构建设置
[build]
  publish = "/"
  command = ""  # 静态 HTML 无需构建命令

# 强制 HTTPS 和域名规范化
[[redirects]]
  from = "http://ulala.jp/*"
  to = "https://ulala.jp/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.ulala.jp/*"
  to = "https://ulala.jp/:splat"
  status = 301
  force = true

# 清理 URL 路径的重定向规则
[[redirects]]
  from = "/search"
  to = "/pages/search.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/pages/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/pages/contact.html"
  status = 200

[[redirects]]
  from = "/notes"
  to = "/pages/notes/index.html"
  status = 200

[[redirects]]
  from = "/notes/*"
  to = "/pages/notes/:splat.html"
  status = 200

[[redirects]]
  from = "/property/*"
  to = "/pages/property/:splat.html"
  status = 200

# 自定义 404 页面
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# 安全和性能优化的头信息
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com;"