[[redirects]]
  from = "http://ulala.jp/*"
  to = "https://ulala.jp/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.ulala.jp/*"
  to = "https://ulala.jp/:splat"
  status = 301
  force = true